### ISSUE TITLE
Server returns 200 OK when repeat until date is before start date.

### ISSUE THREAD

**Issue by sonjoonho** [sonjoonho/mobilise-api#78]
# Expected Behaviour

Error code should be returned.

# Current Behaviour

Server returns 200. A weekday shift is not created. RepeatedShifts table is populated, but the actual shifts are not created.

# Steps to Reproduce

1. Open new shift page. Fill in fields, ensuring that the shift starts on a weekday.
Title: Food Pickup
Description: Repeated shift should be created properly.
Date: 08/07/2019 (a Monday)
Start: 14:00
End: 15:00
Repeat: Weekdays
Repeat until: 14/07/2019
Location: Imperial College London
Roles: Driver's Mate (3)

2. Submit.

3. Observe.

**Comment by wburr10** [comment]
I did exactly what it said here and didn't have the bug locally. I'll try on deployment version

**Comment by wburr10** [comment]
Didn't have the bug on deployment version either.

**Comment by wburr10** [comment]
I mean I'll do the error checking anyways. Just that example isn't right I don't think

**Comment by wburr10** [comment]
Done. Would be worth validating this on front

**Comment by wburr10** [comment]
Done.
